// <auto-generated />
using System;
using MPatel5655.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MPatel5655.Migrations
{
    [DbContext(typeof(MeasurementContext))]
    [Migration("20231006171018_initials")]
    partial class initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MPatel5655.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2003, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diastolic = 79,
                            Systolic = 122
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(1923, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diastolic = 92,
                            Systolic = 142
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2013, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diastolic = 121,
                            Systolic = 181
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
